"use client";
import {useState} from 'react';
type Registration={id:string;role:string;full_name:string;email:string;document_type:string;document_number:string;phone:string;status:string;created_at:string};
export default function RegistrationInbox({token}:{token:string}){
 const [rows,setRows]=useState<Registration[]|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [query,setQuery]=useState('');
 async function load(){if(busy)return;setBusy(true);setError('');try{const res=await fetch('/api/admin/imports',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'list-registrations'}),cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error||'No fue posible consultar los registros');setRows(data.requests);}catch(e){setError((e as Error).message);}finally{setBusy(false)}}
 const visible=rows?.filter(r=>[r.full_name,r.email,r.document_number,r.phone].join(' ').toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es')));
 return <details className="registration-inbox"><summary>Solicitudes de registro de propietarios e inquilinos</summary><p>Datos declarados por el solicitante. Revisa su identidad y relación con los inmuebles antes de habilitar el acceso.</p><button className="button button-secondary" onClick={load} disabled={busy}>{busy?'Consultando…':'Consultar / actualizar registros'}</button>{error&&<p role="alert">{error}</p>}{rows&&<><label>Buscar solicitud<input aria-label="Buscar solicitudes de registro" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nombre, correo, documento o teléfono"/></label><p>Se muestran hasta 500 solicitudes recientes. Vinculación pendiente de revisión.</p><div style={{overflowX:'auto'}}><table><thead><tr><th>Usuario</th><th>Documento</th><th>Contacto</th><th>Estado / fecha</th></tr></thead><tbody>{visible?.map(r=><tr key={r.id}><td>{r.full_name}<small>{r.role==='propietario'?'Propietario':'Inquilino'}</small></td><td>{r.document_type} {r.document_number}</td><td>{r.email}<small>{r.phone}</small></td><td>Pendiente de cruce<small>{new Date(r.created_at).toLocaleString('es-CO',{timeZone:'America/Bogota'})}</small></td></tr>)}</tbody></table>{!visible?.length&&<p>No hay solicitudes con estos filtros.</p>}</div></>}</details>
}
