"use client";
import {useState,type FormEvent} from 'react';
export default function RegistrationForm(){
 const [role,setRole]=useState('propietario');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [done,setDone]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;const data=new FormData(form);setBusy(true);setError('');
 try{const res=await fetch('/api/registro',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...Object.fromEntries(data),role,consent:data.get('consent')==='on'})});const result=await res.json();if(!res.ok)throw new Error(result.error||'No fue posible enviar el registro.');form.reset();setDone(true);}catch(e){setError((e as Error).message);}finally{setBusy(false)}}
 if(done)return <div className="registration-success" role="status"><h2>Solicitud recibida</h2><p>El equipo de Kiosko revisará tus datos y tu relación con los inmuebles. Este registro queda pendiente de validación; te contactaremos para completar el acceso.</p></div>;
 return <form onSubmit={submit}><fieldset disabled={busy}><legend>Tipo de usuario</legend><div className="registration-switch" role="group" aria-label="Tipo de usuario"><button type="button" aria-pressed={role==='propietario'} onClick={()=>setRole('propietario')}>Propietario</button><button type="button" aria-pressed={role==='inquilino'} onClick={()=>setRole('inquilino')}>Inquilino</button></div></fieldset><label>Nombre completo<input name="full_name" autoComplete="name" required minLength={3} maxLength={150} disabled={busy}/></label><label>Correo<input name="email" type="email" autoComplete="email" required maxLength={254} disabled={busy}/></label><div className="form-row"><label>Tipo de documento<select name="document_type" required defaultValue="" disabled={busy}><option value="" disabled>Selecciona una opción</option><option value="CC">Cédula de ciudadanía</option><option value="CE">Cédula de extranjería</option><option value="PAS">Pasaporte</option><option value="NIT">NIT</option><option value="PPT">Permiso por protección temporal</option></select></label><label>Número de documento<input name="document_number" required minLength={4} maxLength={30} pattern="[A-Za-z0-9.-]+" disabled={busy}/></label></div><label>Teléfono<input name="phone" type="tel" autoComplete="tel" required minLength={7} maxLength={25} disabled={busy}/></label><label className="registration-honey" aria-hidden="true">Sitio web<input name="website" tabIndex={-1} autoComplete="off"/></label><label className="registration-consent"><input name="consent" type="checkbox" required disabled={busy}/><span>Autorizo a Kiosko Inmobiliario a utilizar estos datos para revisar mi vinculación con los inmuebles y contactarme sobre mi registro. Puedo solicitar su actualización o retiro en contacto@kioskoinmobiliario.com.</span></label>{error&&<p className="registration-error" role="alert">{error}</p>}<button className="button button-primary submit-button" disabled={busy}>{busy?'Enviando…':'Registrarme'}</button><p className="privacy-note">Tu solicitud será revisada antes de habilitar el acceso a información privada.</p></form>
}
